name: Environment Variable
on:
  workflow_dispatch:
    inputs:
      target_env:
        description: "Chose Environment"
        type: choice
        options: [STAGING, PRODUCTION, TEST]
        default: TEST
      var_name:
        description: "Enter Secters/Variable"
        type: string
        required: true
        default: "TEST_VAR"
jobs:
  PrintEnvVar:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_env }}
    steps:
      - name: Show seleted environment
        run: |
            echo "selected environment: ${{ inputs.target_env }}"
      - name: Display message
        run: |
          echo "Welcome to, ${{ inputs.target_env }}"
          echo "${{ vars.TEST_VAR }} from ${{ inputs.target_env }}"
